const { sqlMap } = require("../db/sqlMap");
const { db } = require("../db/db.js");
const { transport } = require("../mail");
const jwt = require("jsonwebtoken");
const secret = "zyxzyx"; //token密钥
const tokenExpiresTime = 1000 * 60 * 60 * 24 * 7; //token过期时间,毫秒为单位， 7天
const { getPostData } = require("../utils/index");
const defaultAvatar = require("../utils/defaultAvatar");
module.exports = {};
